spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/world?characterEncoding=utf-8&useSSL=false
  redis:
    host:127.0.0.1
    port:6379
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
